### ISSUE TITLE
Basicamente no podes cambiar el pokemon numero 6, problema de index. En la clase player.

### ISSUE THREAD

**Issue by JManuelLorenzo** [Juan-Weyrauch/Segunda_Entrega#19]
![image](https://github.com/user-attachments/assets/03422826-2bf2-4a78-a474-14be357bba5b)

**Comment by Pelle10** [comment]
El error esta ocasionado ya que muestra la lista de los 6 pokemon, incluyendo el que está en combate, pero la lista interna solo cuenta 5 que son lo que no estan peleando por eso suelta error.

**Comment by Juan-Weyrauch** [comment]
En la branch u7-SwitchPokemon se arreglo este problema!
