### ISSUE TITLE
Implementar el uso de los items

### ISSUE THREAD

**Issue by Juan-Weyrauch** [Juan-Weyrauch/Segunda_Entrega#4]
**Actualmente tenemos el 'Attack' funcional, hace falta implementar los items y sus usos**

**Comment by JManuelLorenzo** [comment]
Me dejas el assigament a mi @Juan-Weyrauch ? En cual rama seria?  O tengo que crear una rama para esto y hacer un pull request?

**Comment by JManuelLorenzo** [comment]
Ya hecho en el pr.
