### ISSUE TITLE
Valores de estado sin sentido (ejemplo 35, 40 ,30)

### ISSUE THREAD

**Issue by JManuelLorenzo** [Juan-Weyrauch/Segunda_Entrega#7]
**Al utilizar Chatgpt sin querer puse los valores de estado de cada ataque de una forma incorrecta y sin sentido, deberian ser correspondientes a veneno, quemar, etc. Estan mal.** 
## Ejemplo:
_Vine Whip tiene 10 de ataque y 35 de estado._ _**No tiene sentido**_
<img width="1076" alt="imagen" src="https://github.com/user-attachments/assets/fe383354-b32e-4ed3-bb36-07d4057420a0">

**Comment by Pelle10** [comment]
¿Y eso no se podría cambiar mandando de vuelta a gpt que cambie ese número por unos de los que vayamos a utilizar? Es decir, decirle che cámbiame todos a 0 y después hablamos y cambiamos algún ataque para que tenga estado.
