### ISSUE TITLE
Ataques confusos y vida inicial estatica

### ISSUE THREAD

**Issue by Jesus2santos** [Juan-Weyrauch/Segunda_Entrega#9]
Implementando el ver la vida del pokemon con la impresora pude ver que los ataques son confusos y llego a sospechar de que el pokemon cuando seleccionamos un ataque este se ataca a si mismo, eso lo vi al implementar la vida y realizar un ataque la vida del pokemon adversario aparecia con la vida completa sin embargo cuando mi turno volvia mi pokemon si estaba dañado entonces se me viene a la cabeza 2 hipotesis una el pokemon se daña a si mismo o dos tiene que consumirse 1 turno completo (una accion de cada jugador) para que se efectuen los daños. Otro tema que nos planteamos con Manu es si la vida inicial deberia ser 100 estaticos o deberia variar segun el pokemon, en ese caso como deberiamos incorporarlo? podriamos incorporarlo en la clase create que tambien lo traiga en conjunto con la defensa o poner una variable que sea random de 1 a 55 asi por mas que le salga el maximo algun ataque del pokemon le hara algo de daño.

**Comment by JManuelLorenzo** [comment]
Esto se soluciono
